### ISSUE TITLE
no module named joblib2

### ISSUE THREAD

**Issue by sudeep71** [ablab/quast#108]
Hi 

Just installed quast using conda and making a separate env.

conda create -n quast1 -c bioconda quast

I just ran quast with just a fasta file and i get this error. this is the version of joblib that is installed

joblib             conda-forge/noarch::joblib-0.13.2-py_0
 

No module named joblib2
Traceback (most recent call last)

Any help?

thanks

**Comment by alexeigurevich** [comment]
Hello!
Sorry for the late response due to a summer break. 
It looks like Quast can't find your `joblib` installation. Could you please check that it is indeed available in the same env (`quast1` in your case)? 
To do that, switch to the desired environment and execute:
`python -c 'import joblib'`
If you see an error message like 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named joblib
```
then `joblib` is not available in the environment in the default python.
Just try to install `joblib` in this environment by executing `conda install joblib`. After that, you can try to rerun Quast.

Please let us know if it doesn't work for you and reopen the issue.

**Comment by ajkarloss** [comment]
Hi, I am using quast@5.0.2 in Galaxy 19.05. I am getting the same error as mentioned. I have installed joblib using conda. But still the same error. Any tips?

**Comment by mrmrwinter** [comment]
Hi, Im having this issue but when running standalone QUAST.

I receive the joblib3 error, but this is the results of a traced back error where it cannot find joblib, goes to an exception to look for joblib2 and 3 in python 2, then throws the error.

Traceback (most recent call last):
File "/home/531734/.conda/envs/quast/bin/quast", line 307, in <module>
return_code = main(sys.argv[1:])
File "/home/531734/.conda/envs/quast/bin/quast", line 107, in main
contigs_fpaths, old_contigs_fpaths = qutils.correct_contigs(contigs_fpaths, corrected_dirpath, labels, reporting)
File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 180, in correct_contigs
old_fpaths, corr_fpaths, broken_scaffold_fpaths, logs, is_fatal_error = run_parallel(parallel_correct_contigs, parallel_run_args, n_jobs)
File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 1064, in run_parallel
from joblib3 import Parallel, delayed
`ModuleNotFoundError: No module named 'joblib3'``

Strangely, when i run quast in my environment locally it works, when i run it as a batch job, calling the same environment, it hits the error.

**Comment by alexeigurevich** [comment]
Just for future reference. 
All errors like `no module named joblib2` or (`joblib3`) generally mean that the python interpreter which you are using to run Quast missing `joblib` library. Note that the default Quast behavior is to try to use system-installed `joblib` and only if it is not found, use our custom `joblib2` and `joblib3` packages from the Quast installation package: https://github.com/ablab/quast/tree/master/quast_libs/site_packages (see [here](https://github.com/ablab/quast/blob/master/quast_libs/qutils.py#L1049) how we do such multiple-joblib kinds strategy exactly)

Since embedding third-party Python libs instead of just requiring them as dependencies is a bad software practice, we are going to end such behavior at some point. Moreover, we already did it in `conda` installation and there are no `joblib2/joblib3` packages already. Still, since there are imports of `joblib2/3` inside our code (only if `import joblib` results in `ImportError`), you may face `no module named joblib2` error. To resolve it, just ensure that your proper (!) python has `joblib` installed! E.g. if you run Quast as a batch job, most likely another python interpreter is used there.
