### ISSUE TITLE
TypeError in krona_common_file.write()

### ISSUE THREAD

**Issue by ReneKat** [ablab/quast#109]
Hello All!
I have run metaQUAST on a similar dataset previously with success; however, for two runs I have received the same TypeError when drawing interactive Krona plots at the end of the run. 

Version: 5.0.2, b7350347c

System information:
  OS: Darwin-18.6.0-x86_64-i386-64bit (macosx)
  Python version: 3.6.7
  CPUs number: 8

[metaquast.log](https://github.com/ablab/quast/files/3422027/metaquast.log)

unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/Users/Owl/miniconda3/envs/Shotgun/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg-info/scripts/metaquast.py", line 406, in <module>
    return_code = main(sys.argv[1:])
  File "/Users/Owl/miniconda3/envs/Shotgun/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg-info/scripts/metaquast.py", line 396, in main
    html_saver.create_meta_report(output_dirpath, json_texts)
  File "/Users/Owl/miniconda3/envs/Shotgun/lib/python3.6/site-packages/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
    create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
  File "/Users/Owl/miniconda3/envs/Shotgun/lib/python3.6/site-packages/quast_libs/html_saver/html_saver.py", line 374, in create_krona_charts
    krona_common_file.write(str(sum(lengths)) + '\t' + taxons_for_krona[ref_name] + '\n')
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Any help would be appreciated! Thank you.

**Comment by almiheenko** [comment]
Hi Rene,

This issue was fixed in the master branch some time ago. You can substitute the following file with the attached file:  /Users/Owl/miniconda3/envs/Shotgun/lib/python3.6/site-packages/quast_libs/html_saver/html_saver.py

[html_saver.py.zip](https://github.com/ablab/quast/files/3422150/html_saver.py.zip)

After that, you can rerun MetaQuast with the same parameters and the same output dir -- it will reuse most of the previously generated files and hopefully finish correctly this time.

We plan to include this fix in the upcoming release (5.0.3 or 5.1.0).
Thank you for using our tool!

Best regards,
Alla

**Comment by alexeigurevich** [comment]
This fix was included in the v.5.1.0 release candidate, it is freely available here: https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1

**Comment by ReneKat** [comment]
Hello @almiheenko,
Sorry for the delayed response. This fixed my issue. Thank you for your reply! :)
