### ISSUE TITLE
How to read the circos plot generated

### ISSUE THREAD

**Issue by liuxl18-hku** [ablab/quast#113]
I recently ran quast-lg.py on our human genome assembly with `--split-scaffolds` and `--circos` option.

Here is the circos plot I generated, but I have no idea how to read it, for example, what is "assembly1" and "assembly2", and what is "ANY" means.

![circos](https://user-images.githubusercontent.com/42717675/65650036-abb57900-e03b-11e9-8d8b-84f9d42ef31a.png)

Thank you!

**Comment by alexeigurevich** [comment]
We have some hints about this in the log, e.g. if you run `./quast.py --test --circos`, you may see at the end of the log/stdout:
```
2020-04-30 09:48:41
RESULTS:
  ...
  Circos plot is saved to quast_test_output/circos/circos.png (legend is in legend.txt, configuration file is in circos.conf)
  ...
```

Where circos.png looks like:
![circos](https://user-images.githubusercontent.com/620893/80682508-58247580-8acb-11ea-8226-05d5263b59ee.png)

And `<quast_output_dir>/circos/legend.txt` explains its content:
```
1) The outer circle represents reference sequence with GC (%) heatmap [from 32% (white) to 69% (black)].

2) Assembly tracks:
        assembly1 - contigs_1
        assembly2 - contigs_2
Assembly tracks are combined with mismatches visualization: higher columns indicate larger mismatch rate.

3) User-provided genes. A darker color indicates higher density of genes.
```
In this particular case (a primitive test dataset), there are no mismatches, so there are no columns described in (2) in the legend. As for (3), here you see "gene" and "operon" labels since these types of [genomic features](http://quast.sourceforge.net/docs/manual.html#genomic_feature) were explicitly specified to QUAST. If you provide your file with genes/CDS/etc with just `-g` option, any type of genomic features is considered and thus you see the "ANY" label. 

As for the alignments colors (green/red/etc), the color scheme is equivalent to the original Icarus contig alignment viewer scheme. You may find a detailed legend in the corresponding file: `<quast_output_dir>/icarus_viewers/alignment_viewer.html`. For example: 
![image](https://user-images.githubusercontent.com/620893/80684211-003b3e00-8ace-11ea-8d16-9b13e9ad9830.png)
