### ISSUE TITLE
How to turn on `--debug`?

### ISSUE THREAD

**Issue by SHuang-Broad** [ablab/quast#119]
Hi Alexey,

I'm using QUAST to evaluate several human assemblies (fasta).
For some of them, the contig-to-ref alignment step errored (but quast didn't stop there).

```
ERROR!   4  Failed aligning contigs HG002_M to the reference (non-zero exit code). Run with the --debug flag to see additional information.
```

But I don't see from the help message or the manual where this should be specified, or is there already a place to look for that?
I don't see any error messages from the stdout or stderr attached to that particular assembly.

Thanks!
Steve

**Comment by alexeigurevich** [comment]
You are right, this option is not described anywhere since it is mostly for developers use. Still, you can use it by simply adding `--debug` to your running command. This option will turn on more verbose output and will keep all intermediate files, including huge ones.

However, restarting in `--debug` mode is not necessary in your particular case since all additional information (mentioned in the warning message) is always written to `quast.log` file, while some messages are hidden from console output if `--debug` is not used. So, you should start from looking into the `quast.log` file and probably further read `*.stderr` files mentioned there, in which `stderr` stream of contig-to-ref alignment software (minimap2) is redirected.

I will keep this issue open since we should deal with this and similar confusing warning messages.

**Comment by SHuang-Broad** [comment]
A related issue is that, I think the error is probably due to low memory (though I do have a 70GB machine for this purpose, the task seem to be using 69 G out of that).
So I am thinking about, is it possible to cap memory usage, just like `--threads`? (I know there's the `--memory-efficient` option, but it'd be better if one can specify both thread and memory caps).
Definitely not high priority.

**Comment by alexeigurevich** [comment]
I am closing this issue since in v.5.1.0 (see published release candidate [here](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1)) the mentioned problem is solved -- a better warning message is given in such situation without confusing and excessive info on `--debug`. 

We also improved documentation and warning messages regarding `--memory-efficient` option. Essentially it just sets `--threads` to 1, you may be interested in setting it to `2` or even a larger number to fit into your memory limit but get results faster.

Note that we can technically implement an option like `--max-memory <MAXMEM>` but it would be the same as running QUAST with `ulimit -m <MAXMEM>` and cause a crash of the pipeline if actual memory usage exceeds MAXMEM.
