### ISSUE TITLE
Discuss the possibility of creating a QUAST package for DebianMed

### ISSUE THREAD

**Issue by michaelbarton** [ablab/quast#14]
After an initial discussion with @smoe by email, I'd like to start a discussion
here of possibly creating a Debian package for QUAST. As QUAST is becoming more
and more widely used in the genomics community, a Debian package could further
increase adoption by making it simpler to install.

I think it would be possible to create a debian package from the source
distribution. One point to consider though is that many of the bundled
dependencies in the QUAST package (e.g. mummber) are all already available in
DebianMed so it could be the case that only QUAST scripts would be required,
along with updates to $PATH.

I've opened this issue to see if I, @smoe, @pbelmann and the QUAST team might
find this to be a worthwhile exercise.

**Comment by hmontenegro** [comment]
There are issues related to some dependencies which have non-free licenses (academic-only). 

I have no experience packaging stuff, but as you said, probably the best would be to have different packages for all dependencies, and a package for QUAST scripts alone.

**Comment by alexeigurevich** [comment]
Just want to notice here: we released v.4.3 which include setup.py installer based on python standard setuptools module. I think this is a step forward in a way to Debian package for QUAST.

**Comment by michaelbarton** [comment]
Thanks for following up. I think one way to make this simpler to install would be to provide the option of using the required third-party tool if they are on the path. This would then allow a package manager to download and install the required packages. I understand that this sort of thing might not be top priority for your project.

**Comment by michaelbarton** [comment]
I will close this issue as no longer being active. We should still keep in mind that at some point in future, creating debmed or @sjackman's homebrew science packages would be a useful of contributing our build recipes for others to use outside of docker.

**Comment by alexeigurevich** [comment]
Hi @michaelbarton, actually there is @sjackman's homebrew science package already (since version 4.1 and it is currently updated to the latest 4.4 release). Sorry for not mentioning this here earlier!

**Comment by smoe** [comment]
Hello @michaelbarton,
 
I have admittedy forgotten about QUAST. However, the [Debian Covid-19 hackathon](https://salsa.debian.org/med-team/community/2020-covid19-hackathon/-/blob/master/202006_Debian-Med_hackathon.md) features it as a dependency for nf-core viralrecon pathway and thus it got back on the radar. You can follow our progress on https://salsa.debian.org/med-team/quast/ . 

The package is just at a stage that it all compiles and installs, testing is now a bit of a hurdle since Debian cannot accept to download extra data at build-time. Also, GeneMark is not redistributable and had to be removed. Other tools are already shipping with Debian so we have removed them also and adjusted the build. The directories that were excluded you find in the [d/copyright](https://salsa.debian.org/med-team/quast/-/blob/master/debian/copyright) file.

Many thanks and regards,

Steffen
