### ISSUE TITLE
Long work time 

### ISSUE THREAD

**Issue by artempronozin95** [ablab/quast#144]
Dear authors,
I have a question about work time process.
As the reference genome use this one: 
ftp://ftp.ensemblgenomes.org/pub/plants/release-47/fasta/triticum_aestivum/dna/Triticum_aestivum.IWGSC.dna.toplevel.fa.gz
As gff file use:
 ftp://ftp.ensemblgenomes.org/pub/plants/release-47/gff3/triticum_aestivum/Triticum_aestivum.IWGSC.47.gff3.gz 
Then transform them into "real" gff (because original is out of work).
So i established the the process by next command
...**/quast.py scaffolds.fa contigs.fa -r Triticum_aestivum.IWGSC.dna.toplevel.new.fa -g Triticum_aestivum_new.gff --large --gene-finding --rna-finding -o ./**
It already work for a week, the process **stuck** on:
**Running Genome analyzer...
  NOTICE: No file with operons were provided. Use the -O option if you want to specify it.
  Loaded 1620887 genomic features of type "ANY"
  1  scaffolds
  2  contigs**
is it normal, or i have the error?
P.S. the files in "genome_stats" folder upgreat every hour.

Thanks for answer.
With respect,
Artem Pronozin.

**Comment by alexeigurevich** [comment]
Dear Artem,
Since Triticum aestivum genome is huge (~17 Gb), I suppose the processing may really be so time-consuming. Taking into account regular updates of the files under the "genome_stats" folder, it looks like Quast is computing something and not just stuck permanently.

Note that Genome analyzer is not well optimized for large genomes and we tested it at max on Human-size genomes (~3 Gb). 

My suggestions are either (a) to wait a bit more (can't estimate how much it may take unfortunatelly), or (b) rerun without the GFF (you can use the same output folder to reuse already completed results, e.g. contig/scaffold alignments results would be reused), or (c) rerun with the GFF but focus only on a subset of all features (e.g. process only `CDS` or `exon` entries, to do so, specify the file like `--features CDS:Triticum_aestivum_new.gff` or `--features exon:Triticum_aestivum_new.gff`, however, I am not sure that this would give a significant speedup in your case).

I would recommend option (b) and get all key Quast stats except the number of assembled genomic features. We will try to improve the Running Genome analyzer stage performance on huge genomes somehow, but it is not in the near future development plans.

**Comment by artempronozin95** [comment]
Thank you so much for answering

пн, 13 июл. 2020 г. в 20:13, alexeigurevich <notifications@github.com>:
