### ISSUE TITLE
busco or not busco ?

### ISSUE THREAD

**Issue by EricDeveaud** [ablab/quast#147]
Hello,

looking at #4 one can see 
`Busco was removed from the master branch, so closing this issue as not related to quast project anymore.`

tis was said on april 2016

release 5.0.2 tagged on november 2018 still show busco option
```
[gensoft@c7baf856ae31 5.0.2]$ quast.py --version 
QUAST v5.0.2
[gensoft@c7baf856ae31 5.0.2]$ quast.py -h | grep -i busco
-b  --conserved-genes-finding         Count conserved orthologs using BUSCO (only on Linux)
```

what is the status of busco for quast/5.0.2 ?

regards

Eric

**Comment by alexeigurevich** [comment]
BUSCO was used in the pipeline for a while in 2015-2016 as an experimental module (in the master branch, but not released), then we decided to remove it as mentioned in #4. However, later in 2018, it was added again (together with many other changes during the QUAST-LG project development). So, BUSCO is inside the official (released) version of QUAST since v.5.0.0 and ongoing. Still, note that BUSCO is available only for Linux.

**Comment by EricDeveaud** [comment]
thanks for the explanation
any ETA for next release ? 5.1.0

**Comment by alexeigurevich** [comment]
I expect "someone in summer" but note that we failed to meet some of our previous ETAs :(
Currently, we have [5.1.0rc1](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) that you can try already.

**Comment by EricDeveaud** [comment]
exept for flights ETAs are made to be by delayed ;-)
