### ISSUE TITLE
Not found in the NCBI database!

### ISSUE THREAD

**Issue by parharn** [ablab/quast#151]
Hi, I am testing metaquast 4.5.4 on a scaffold data set of E.coli. I am running it without reference so that if it works fine I run it on a metagenomics dataset. However, it seems to not be able to retrieve the references from NCBI that it has found on SILVA, even though they are very commong ones. Any obvious reason why I get this? 

[metaquast.log](https://github.com/ablab/quast/files/5096813/metaquast.log)

**Comment by Qiuyu-dot** [comment]
Hi, parharn,

I encountered the same issue. May i know that have you fixed it? Or can you download the database from somewhere else?

**Comment by alexeigurevich** [comment]
I am closing this issue due to no info or activity for a long time.

For future reference: we recommend to try the [latest stable version first](https://github.com/ablab/quast/releases/latest), maybe this issue was solved there already. 
If someone encouraged the same issue, please reopen and attach your metaquast.log file.

Note: recently pre-released version 5.1.0rc1 bases its search on the new SILVA v.138 database (in contrast to the old v.123 in the previous stable release 5.0.2). However, SILVA database has changed its taxonomy format a bit in the newest versions which may cause problems with downloading of many references. This issue is fixed [here](https://github.com/ablab/quast/commit/904eab1202cbb57df7f7ff306356c801e692a8ce). The fix will be included in v.5.1.0rc2 or stable 5.1.0 release.
