### ISSUE TITLE
Trouble downloading keras

### ISSUE THREAD

**Issue by nataliemur26** [ablab/quast#156]
I am trying to download keras in anaconda and I get the following error:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - keras -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by alexeigurevich** [comment]
Hi!
It seems that this issue is not relevant to our tool since we don't use `keras` inside.

Still, I would like to mention here that the current stable Quast release v.5.0.2 (available from `bioconda` channel) is not compatible with Python 3.8, unfortunately. So, potentially it may cause some issues with `conda` if you need both Quast and some other package requiring Python 3.8+. 
We fixed the 3.8-incompatibility issue already in the master branch and in our v.5.1.0rc1 pre-release but it is not available at `bioconda` yet. We plan to add it there when the official v.5.1.0 release will be out (somewhen soon..).
