### ISSUE TITLE
Installing quast via conda fails

### ISSUE THREAD

**Issue by SKNBE** [ablab/quast#189]
As I mentioned in the header, installing quast via conda fails.

conda install -c bioconda quast Collecting package metadata (current_repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. Collecting package metadata (repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve.

I have installed Quast via conda before and therefore I was wondering if someone else is no longer able to install Quast via conda.

**Comment by venuraherath** [comment]
> I have the same problem. Some of the other programs I have installed use python 3.8 as the lowest version, so I had to install QUAST in a separate environment

Same here. Got it working in python=3.6.

**Comment by alexeigurevich** [comment]
That is strange since v.5.2.0 is available for Python 3.8 and above via conda (since July 2022, so the April 2022 comment above and earlier comments make sense). 
E.g., see [here](https://anaconda.org/bioconda/quast/files) the list of available conda builds that includes packages for py38, py39, and py310 for Linux and OSX (as well as versions for py27 and py36, py37). Could it be a Quast-unrelated conda conflict in your case?
If it is indeed a Quast-related issue, please post here the conda error log and reopen the issue.
