### ISSUE TITLE
Beginner. Can't get Fastq file open. 

### ISSUE THREAD

**Issue by banuelos3** [ablab/quast#194]
Hello all, this is my first time running QUAST. I have downloaded my fastq files and put them into a folder called "Maiz" and copy and pasted the file name so I know that's right. I've copy and pasted the code I run and the error I get below.  

quast-5.0.2 % ./quast.py Maiz/Zm11_HH5NHDSX2_L3_1.fq /
ERROR! File not found (contigs): Maiz/Zm11_HH5NHDSX2_L3_1.fq

Any advice for a beginner? I'm not sure what I'm doing wrong because I did it just like the test data. 

Please let me know what you think. Thank you

**Comment by alexeigurevich** [comment]
Hi,
First, please check that your file path is indeed correct with some standard command-line utility like `ls` to check whether the issue is Quast-related or generic:
```ls Maiz/Zm11_HH5NHDSX2_L3_1.fq```

When Quast reports "File not found" it always means the provided path is incorrect, most often due to misprints or the incorrect use of a relative path. You may try to use the absolute path to your file and check whether it helps.

Second (!!!), Quast accepts genome assemblies (usually in the FASTA format with .fa or .fasta extension), not raw sequencing reads (usually in the FASTQ format with .fq or .fastq extension). Make sure that you are providing proper data as input.
