### ISSUE TITLE
uninstall quast compiled from source

### ISSUE THREAD

**Issue by emasve** [ablab/quast#197]
Dear all,

Can somebody please help me uninstall quast and its dependencies which were installed from source as desribed in manual and below. 
I am using wsl-ubuntu in windows 10. The quast was installed in /usr/local/lib/

Installation:
quast-5.0.2
wget https://downloads.sourceforge.net/project/quast/quast-5.0.2.tar.gz
    tar -xzf quast-5.0.2.tar.gz
    cd quast-5.0.2

sudo  setup.py install

I am quite a beginner and my computer is getting cramped, otherwise nothing wrong with quast :)

**Comment by alexeigurevich** [comment]
Hi!

There is no easy way to uninstall quast after `sudo setup.py install` ;)

I think the simplest way to remove _most_ of the quast-related files would be to execute
`sudo rm -rf /usr/local/lib/quast*`
`sudo rm -rf /usr/local/lib/python*/dist-packages/quast*`

If you want to remove absolutely everything, I have found a more [detailed instruction](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall) at StackOverflow. Note that you likely need to run the removal command (`xargs rm -rf < files.txt`) with `sudo` since you installed quast with `sudo`.

For the future, please prefer installing quast from conda (`conda install -c bioconda  quast`) or from pip (`pip install quast`), since these package managers manage removal as well. **Or** you can simply download quast .tar.gz, unpack it, and start using it right from that location **without any further installation**. In this case, uninstalling would be simply removing the unpacked directory.

Finally, in some advanced cases, e.g., if you use Quast in the metaQuast mode without reference genomes, Quast may download additional databases/binaries and put them into your home directory under `~/.quast/`. If that is the case, you may want to remove them as well with `rm -rf ~/.quast/` (no `sudo` is needed here).
