### ISSUE TITLE
Broken Test Run

### ISSUE THREAD

**Issue by AlohaPropolis** [ablab/quast#198]
While playing around with the quast test run I try redirecting the output using -o option the new output directory could not be found and I received two warnings. I then removed the redirect option and reran the test script and this time it could not find the reference test data. Its seem I may have charged the location of the test data to an unknown location.
[quast.log](https://github.com/ablab/quast/files/7817666/quast.log)
Ps: I am a newbie!

**Comment by alexeigurevich** [comment]
Hi!
> While playing around with the quast test run I try redirecting the output using -o option the new output directory could not be found

The test run (`--test`) implicitly hardcodes inputs and outputs, so the output directory is always `quast_test_output` and cannot be changed via `-o`. Still, you can "emulate" the test run simply with `quast.py -r test_data/reference.fasta.gz test_data/contigs_*.fasta --gene-finding --glimmer -g test_data/genes.gff --operons test_data/operons.gff -o ANY_OUTPUT_DIR`.

> and I received two warnings.

The warnings are not related to your "playing around". One is about failed Glimmer compilation, you should check the actual reason in the log (`/opt/anaconda3/lib/python3.7/site-packages/quast-5.0.2-py3.7.egg/quast_libs/glimmer/src/make.err`) and try to fix it. Another is about expired GeneMark license, to update it please follow the instructions in the log:
> To update license, please visit http://exon.gatech.edu/GeneMark/license_download.cgi page and fill in the form.
You should choose GeneMarkS tool and your operating system (note that GeneMark is free for non-commercial use).
Download the license key and replace your ~/.gm_key with the updated version. After that you can restart QUAST.

> I then removed the redirect option and reran the test script and this time it could not find the reference test data. Its seem I may have charged the location of the test data to an unknown location.

Note that in the attached log the data is located correctly. Also note that since you installed Quast via `bioconda`, the test data is not included in the installation package, but you can always download it in the current directory (~4 MB). This can be done via
`wget quast.sf.net/test_data.tar.gz && tar xzf test_data.tar.gz`

> Ps: I am a newbie!

Welcome! Let us know if you have any further questions.
