### ISSUE TITLE
Version of installed minimap2 differs from its version in the QUAST package (2.24)

### ISSUE THREAD

**Issue by Meer9234** [ablab/quast#252]
Hi,

I cannot use quast with the -r command. I get this warning:
WARNING: Version of installed minimap2 differs from its version in the QUAST package (2.24). Please make sure that you use an actual version of software.
I have installed minimap2 v2.26 so do I get and Error because quast is not compatible anymore with the newer version of minimap2?

The error files just state this:
[M::mm_idx_gen::39.411*0.78] collected minimizers

Thanks in advance!

**Comment by alexeigurevich** [comment]
Hi (and sorry for the delay),

This is just a warning because we tested the release with v.2.24 (the latest at that time), so we were not 100% sure about previous or later versions. But I just checked the latest Quast release (v5.2.0) on systems with pre-installed minimap2 v.2.26 (via conda/brew on Linux/Mac) and it worked just fine, i.e. with the warning about the installed minimap2 version but without errors and everything was aligned correctly.
Have you tried to run `quast.py --test` (which involves the alignment with minimap2)? 
Maybe something is wrong with your specific assembly or reference file but not Quast in general. In this case, please reopen the issue and attach a minimal portion of your files so that I can reproduce and debug the issue.
