### ISSUE TITLE
ERROR! Skipping S7KLEB_S14_L001_R2_001.fastq.00.0_0.cor.fastq.gz because it contains non-ACGTN characters.

### ISSUE THREAD

**Issue by linuxuser77771344** [ablab/quast#254]
command: quast *fastq.gz 
![image](https://github.com/ablab/quast/assets/147368191/aec19fe8-8082-408e-a594-04bf27480566)

**Comment by alexeigurevich** [comment]
Quast evaluates genome assemblies, not raw sequencing reads, so our typical input is FASTA files (which don't contain non-ACGTN characters), not FASTQ files (which do). 
You can provide FASTQ files as _additional_ input to make the assembly evaluation more advanced but you need to prepend the file paths with the corresponding command-line options in this case (e.g., `-1` and `-2`, see more in the manual or via `quast.py --help`). By default, Quast treats all inputs not prepended with a command-line option as a genome assembly file, so it doesn't expect to see non-ACGTN characters there and crashes otherwise.
