### ISSUE TITLE
Metaquast Failed aligning contigs

### ISSUE THREAD

**Issue by lauj8** [ablab/quast#31]
Hi, I've successfully run metaquast a few times without a reference, but one data set is giving me this error: 
Failed aligning the contigs for all the references. Try to use option --max-ref-number to change maximum number of references (per each assembly) to download.

It looks like there are 121 reference genomes that are retrieved, and I set the --max-ref-number as 200. Do you know what could be the issue? Attached in the metaquast log in case that is helpful.

Thank you.

-Jennifer

[metaquast.log.txt](https://github.com/ablab/quast/files/1151406/metaquast.log.txt)

**Comment by alexeigurevich** [comment]
Hi Jennifer,
I am very sorry but we missed your issue during the summer holiday. I am closing it now since it is most probably outdated. Could you please reopen if the problem persists. According to the log, something it with the aligner but this log is not very informative, the most interesting is quast.log on the combined reference which is in `/workspace/lauj8/NM4_fastq_trimmed/NM4_megahit_out_PPmice/NM4_micePP_megaquast200.a/combined_reference/quast.log`
