### ISSUE TITLE
BUSCO's Augustus crashes

### ISSUE THREAD

**Issue by ad3002** [ablab/quast#4]
I got Augustus crash with this error:

```
* glibc detected * /home/akomissarov/libs/quast/libs/Busco/augustus-3.0.3/bin/augustus: double free or corruption (fasttop): 0x00000000019
a9820 *
```

When I run it with --debug I did not get it. Or it was silenced.

**Comment by charmichaeld** [comment]
I encountered the same error when I ran BUSCO using the '--mode all' option with my Candida albicans genome build:
> python ./BUSCO_v1.1b1.py --in my_build.fa --mode all --species candida_albicans --cpu 18 --lineage /BUSCO/fungi -o candida_albicans -f

More specifically here is the command that is failing during the BUSCO processing (there are six of these each resulting in a core dump):
> augustus --proteinprofile=/scratch/datasets/BUSCO/fungi/prfl/BUSCOfEOG7MH16D.prfl --predictionStart=179320 --predictionEnd=189523 --species=candida_albicans "Ca21chr4_C_albicans_SC5314candida_albicans_.temp"

I ran that augustus command manually outside of the BUSCO python script as it is and there was a core dump. I ran it again using the option --genemodel=intronless as follows and there were not any errors and predicted genes were printed. (I used intronless because most of candida_albicans genes are intronless.)

> augustus --genemodel=intronless --proteinprofile=/scratch/datasets/BUSCO/fungi/prfl/BUSCOfEOG7MH16D.prfl --predictionStart=179320 --predictionEnd=189523 --species=candida_albicans "Ca21chr4_C_albicans_SC5314candida_albicans_.temp"


However, I don't see a way to specify the augustus --genemodel=intronless option when running BUSCO_v1.1b1.py

**Comment by davidlawood** [comment]
Hi, I've been getting this error too with the command:
```
BUSCO.py -in seq.fa -l fungi -o seq_out -c 12 -f
```
Did you find a cause/solution for this?

**Comment by charmichaeld** [comment]
I've communicated with the BUSCO developers and they are working on making it possible to add augustus options when running the BUSCO.py script. As a workaround, you can edit your BUSCO.py file and add the option --genemodel=intronless to the augustus commands. I added it to three lines in the BUSCO_v1.1b1.py script that run the augustus command and there were no core dump errors. It worked for my genome because it is a fungus with very few genes having introns.

change 3 lines beginning like this:
>command='augustus --proteinprofile=

to this:
>command='augustus --genemodel=intronless --proteinprofile=

**Comment by alexeigurevich** [comment]
Busco was removed from the master branch, so closing this issue as not related to quast project anymore.
