### ISSUE TITLE
Inconsistent requirements for submodules

### ISSUE THREAD

**Issue by SethosII** [ablab/quast#41]
I found some inconsitencies regarding the required software for submodules. The [README](https://github.com/ablab/quast) says:

> For the optional submodules:
>
>    Time::HiRes perl module for GeneMark-ES (needed when using --gene-finding --eukaryote)
>    Java 1.8 or later for GRIDSS (needed for SV detection)
>    R for GRIDSS (needed for SV detection)

and the [manual](http://quast.bioinf.spbau.ru/manual.html) states:

> In addition, QUAST submodules require:
>
>    Java JDK (tested with OpenJDK 6) for GAGE
>    Time::HiRes perl module for GeneMark-ES
>    Boost (tested with v1.56.0) for E-MEM

Which of them is correct and can you update them to be consistent?

**Comment by alexeigurevich** [comment]
Hi @SethosII, the online manual is for the latest release which is 4.6.1 (as stated in the manual). This release requirements are properly specified there. Github master branch is for 5.0.0-dev release which is significantly different from 4.6.1. In particular we added GRIDSS and removed GAGE and E-MEM. So, README file at github has also correct requirements for submodules but it is related to a different QUAST version rather than the online manual. 

As soon as we publicly release 5.0.0, the online manual will also be updated with the new requirements.

P.S. Anyway, I have just slightly updated manual.html in the repo to be consistent with README there.
