### ISSUE TITLE
Summary stats different with quast4.5 and quast4.6

### ISSUE THREAD

**Issue by jaworskicoline** [ablab/quast#43]
Hello,
I have recently downloaded the new quast version (4.6.1), and I ran it on one of my assemblies; it is indeed much faster. I found some unexpected results in the general stats (report.txt), especially regarding genome fraction, so I also ran the former version (4.5), below is the comparative table.

1/ How can you explain the difference ?
2/ How did you have quast4.6.1 performing much faster ? Is there something changed in the algorithm, and especially regarding definitions (e.g., of misassemblies) and alignment thresholds ?

Thank you very much for your answer.
Best regards,
Coline Jaworski

------------------------------------------------------------------------------------------------------------
Assembly | Quast4.5 | Quast4.6.1
-- | -- | --
 contigs (>= 0 bp) | 261 | 261
 contigs (>= 1000 bp) | 261 | 261
 contigs (>= 5000 bp) | 261 | 261
 contigs (>= 10000 bp) | 260 | 260
 contigs (>= 25000 bp) | 235 | 235
 contigs (>= 50000 bp) | 150 | 150
Total length (>= 0 bp) | 159,478,338 | 159,478,338
Total length (>= 1000 bp) | 159,478,338 | 159,478,338
Total length (>= 5000 bp) | 159,478,338 | 159,478,338
Total length (>= 10000 bp) | 159,473,207 | 159,473,207
Total length (>= 25000 bp) | 158,969,480 | 158,969,480
Total length (>= 50000 bp) | 155,802,267 | 155,802,267
 contigs | 261 | 261
Largest contig | 9,888,897 | 9,888,897
Total length | 159,478,338 | 159,478,338
Reference length | 153,681,346 | 153,681,346
GC (%) | 39.63 | 39.63
Reference GC (%) | 39.85 | 39.85
N50 | 3,799,886 | 3,799,886
NG50 | 3,799,886 | 3,799,886
N75 | 1,355,015 | 1,355,015
NG75 | 1,528,338 | 1,528,338
L50 | 14 | 14
LG50 | 14 | 14
L75 | 32 | 32
LG75 | 29 | 29
 misassemblies | 5,500 | 3,698
 misassembled contigs | 231 | 214
Misassembled contigs length | 158,499,367 | 104,931,326
 local misassemblies | 10,392 | 6,454
 unaligned mis. contigs | 25 | 42
 unaligned contigs | 1  249 part | 1  249 part
Unaligned length | 10,118,222 | 53,286,055
Genome fraction (%) | 93.03 | 65.89
Duplication ratio | 1.05 | 1.05
 N's per 100 kbp | 0.00 | 0.00
 mismatches per 100 kbp | 329.83 | 342.27
 indels per 100 kbp | 248.43 | 249.18
Largest alignment | 518,864 | 518,864
Total aligned length | 149,357,462 | 106,208,216
NA50 | 82,893 | 29,721
NGA50 | 86,330 | 34,756
NA75 | 33,455 | 885
NGA75 | 39,352 | 794
LA50 | 530 |  
LGA50 | 496 |  
LA75 | 1277 |  
LGA75 | 1157 |

**Comment by alexeigurevich** [comment]
Hi, Coline!
This looks weird.
I suggest that the issue is because some contigs which were previously classified as "misassembled" are now classified as "unaligned mis. contigs" and thus their misassemblies are not counted in "# misassemblies" in 4.6.1 report. However, it is still rather strange behaviour we have not changed the definitions between 4.5 and 4.6 and just fine tune some params in misassemblies detection algorithm in some complex cases. 
Could you please provide us with your reference and assembly files for debugging? You can upload them somewhere and post a link here or send us privately via support email (quast.support@cab.spbu.ru).
Thanks!

**Comment by jaworskicoline** [comment]
Thank you for your answer, I am currently working on unpublished materials so I would ask you to keep it strictly confidential (I will send an email with the links once upload is done).
I have also run a test on an assembly built from public Dmel data, and the differences between the outputs from the two quast versions are minimal, but still exist (please see below). It indeed looks like something related to the detection of misassemblies.
Thank you very much.
Best reagrds,
Coline
------------------------------------------

Dmel | Quast4.5 | Quast4.6.1
-- | -- | --
 contigs (>= 0 bp) | 348 | 348
 contigs (>= 1000 bp) | 348 | 348
 contigs (>= 5000 bp) | 348 | 348
 contigs (>= 10000 bp) | 346 | 346
 contigs (>= 25000 bp) | 302 | 302
 contigs (>= 50000 bp) | 199 | 199
Total length (>= 0 bp) | 126,850,418 | 126,850,418
Total length (>= 1000 bp) | 126,850,418 | 126,850,418
Total length (>= 5000 bp) | 126,850,418 | 126,850,418
Total length (>= 10000 bp) | 126,835,139 | 126,835,139
Total length (>= 25000 bp) | 125,993,512 | 125,993,512
Total length (>= 50000 bp) | 122,305,633 | 122,305,633
 contigs | 348 | 348
Largest contig | 7,973,719 | 7,973,719
Total length | 126,850,418 | 126,850,418
Reference length | 137,547,960 | 137,547,960
GC (%) | 41.94 | 41.94
Reference GC (%) | 42.08 | 42.08
N50 | 1,344,309 | 1,344,309
NG50 | 1,298,403 | 1,298,403
N75 | 756,410 | 756,410
NG75 | 452,266 | 452,266
L50 | 22 | 22
LG50 | 26 | 26
L75 | 51 | 51
LG75 | 65 | 65
 misassemblies | 935 | 940
 misassembled contigs | 204 | 204
Misassembled contigs length | 92,516,971 | 92,516,971
 local misassemblies | 475 | 471
 unaligned mis. contigs | 24 | 24
 unaligned contigs | 5  116 part | 5  116 part
Unaligned length | 1,598,811 | 1,598,720
Genome fraction (%) | 89.392 | 89.389
Duplication ratio | 1.019 | 1.019
 N's per 100 kbp | 0.00 | 0.00
 mismatches per 100 kbp | 9.48 | 9.47
 indels per 100 kbp | 13.21 | 13.20
Largest alignment | 2,804,835 | 2,804,835
Total aligned length | 125,218,696 | 125,218,825
NA50 | 845,636 | 845,636
NGA50 | 756,410 | 756,410
NA75 | 364,301 | 364,301
NGA75 | 236,150 | 236,150
LA50 | 47 | 47
LGA50 | 53 | 53
LA75 | 103 | 103
LGA75 | 131 | 131

**Comment by alexeigurevich** [comment]
Hi Coline,
Sorry for the delay! We found the bug (it is on our side). I've created a bugfix branch for the new 4.6.2 release: https://github.com/ablab/quast/tree/release_4.6.2
It include the bugfix for your issue and one more tiny bugfix.
Note that the bug was rather specific and could occur only in few case and only if --min-alignment is relatively large (>500), so you very (un)lucky to catch it!
After applying the bugfix, the stats became pretty similar (showing only the most interesting part here):

---
Metric | Quast4.5 | Quast4.6.2
-- | -- | --
misassemblies | 5,500 | 5,497
misassembled contigs | 231 | 231
Misassembled contigs length | 158,499,367 | 158,499,367
local misassemblies | 10,392 | 10,379
unaligned mis. contigs | 25 | 25
unaligned contigs | 1 + 249 part | 1 + 249 part
Unaligned length | 10,118,222 | 10,267,550
Genome fraction (%) | 93.03 | 92.934
Duplication ratio | 1.05 | 1.045
---

You can use the branch now and I think we will release it soon (in 1-2 days after all tests are passed).

**Comment by alexeigurevich** [comment]
@jaworskicoline the fixed version was released! Please feel free to try official 4.6.2 at https://sourceforge.net/projects/quast/files/
