### ISSUE TITLE
Output directory already exists

### ISSUE THREAD

**Issue by sjackman** [ablab/quast#44]
When the output directory already exists, but is empty, I see this message:
```
NOTICE: Output directory already exists. Existing Minimap2 alignments can be used
```

This run of QUAST then later exited with an exit status of 1. The last message it displayed was:
```
Running Basic statistics processor...
```

I'm not sure if the two are related, but the `NOTICE` is misleading in any case, since the Minimap2 alignments don't exist in the empty directory.

**Comment by sjackman** [comment]
I find it useful to create the empty output directory first and store the log files from the SLURM schedule in the output directory of QUAST.

**Comment by alexeigurevich** [comment]
Hi, Shaun!
I improved the handling of output dirs -- now we report a notice only if the dir exists and contains `quast.log` (or `metaquast.log`) file. Also, the notice message is updated, since we reuse not only Minimap2 alignments but a few other things, too.

As for the the "error code 1" issue -- it is not related to this issue. Please create another issue if this error reproduces one more time (I am not sure what has happened there, so please try to add more detailed description, please).
