### ISSUE TITLE
"This contig is more unaligned than misassembled" counts Ns

### ISSUE THREAD

**Issue by sjackman** [ablab/quast#48]
```
This contig is misassembled.
Warning! This contig is more unaligned than misassembled. Contig length is 18494 and total length of all aligns is 8494
	Alignment: 43285440 43292966 | 1 7535 | 7527 7535 | 98.93 | CM000681.2_Homo_sapiens_chromosome_19__GRCh38_reference_primary_assembly 10725403_8495_0_5261205__..._10482123
	Alignment: 43232488 43233446 | 17536 18494 | 959 959 | 99.9 | CM000681.2_Homo_sapiens_chromosome_19__GRCh38_reference_primary_assembly 10725403_8495_0_5261205__..._10482123
Unaligned bases: 10000
```
This contig is composed of 8,494 nucleotides and 10,000 N. The unaligned portion is entirely Ns. I believe the number of Ns should not count toward either the unaligned length or the contig size. In this case, 100% of the non-N portion of the contig is aligned.

**Comment by alexeigurevich** [comment]
Hi, Shaun!
Thanks for noticing that. We recently skipped counting Ns in the number of unaligned bases and related metrics, so this modification for partially unaligned contigs goes straight in line with it.
We've just added the fix for this issue: https://github.com/ablab/quast/commit/0566c2181292af22f076e8e1e478d30b485d234a (sorry, missed issue ID in the message, so it is not tracked here).

**Comment by sjackman** [comment]
Thanks for the quick fix, Alex!
