### ISSUE TITLE
quast.py --test -> Warning occured 

### ISSUE THREAD

**Issue by AGoepfert** [ablab/quast#5]
Hello,

when I am running python quast.py --test following warning occured.

But metaquast.py --test PASSED without any notes.

Could you help me with that?
___________________________
Quast.log

unning GAGE...
  1  contigs_1...
  2  contigs_2...
  1  Logging to files gage_contigs_1.stdout and gage_contigs_1.stderr...
  2  Logging to files gage_contigs_2.stdout and gage_contigs_2.stderr...
  1  sh libs/gage/getCorrectnessStats.sh quast_test_output/quast_corrected_input/reference.fasta \
     quast_test_output/quast_corrected_input/contigs_1.fasta quast_test_output/gage/tmp \
     500 > quast_test_output/gage/gage_contigs_1.stdout 2> quast_test_output/gage/gage_contigs_1.stderr
  2  sh libs/gage/getCorrectnessStats.sh quast_test_output/quast_corrected_input/reference.fasta \
     quast_test_output/quast_corrected_input/contigs_2.fasta quast_test_output/gage/tmp \
     500 > quast_test_output/gage/gage_contigs_2.stdout 2> quast_test_output/gage/gage_contigs_2.stderr
     The tool returned non-zero. See quast_test_output/gage/gage_contigs_1.stderr for stderr.
  1  Failed.
     The tool returned non-zero. See quast_test_output/gage/gage_contigs_2.stderr for stderr.
  2  Failed.
WARNING: Error occurred while GAGE was processing assemblies. See GAGE error logs for details: /quast-master/quast_test_output/gage/gage_*.stderr

____________________________
gage_*.stderr

/quast-master/libs/gage/getCorrectnessStats.sh: 35: /quast-master/libs/gage/getCorrectnessStats.sh: javac: not found
/quast-master/libs/gage/getCorrectnessStats.sh: 36: /quast-master/libs/gage/getCorrectnessStats.sh: javac: not found
/quast-master/libs/gage/getCorrectnessStats.sh: 37: /quast-master/libs/gage/getCorrectnessStats.sh: javac: not found
Error occurred during compilation of java classes (/quast-master/libs/gage/*.java)! Try to compile them manually!

**Comment by alexeigurevich** [comment]
Hi,
Could you please send such messages to quast.support@bionf.spbau.ru?

The answer to this issue is rather clear. You see problems in log: "javac: not found". This means that you don't have javac command (Java Compiler from Java JDK package). Java is needed for GAGE module which is included in quast.py --test, but not included in metaquast.py --test.  Actually, GAGE is a third-party tool which is in depended from QUAST but some quast.py users want to use --gage option, that is why we included it in quast.py --test.

We have a notification in the manual, that Java JDK is needed for using GAGE (see here: http://quast.bioinf.spbau.ru/manual.html#sec2.3)
