### ISSUE TITLE
trouble opening html report

### ISSUE THREAD

**Issue by zrlewis** [ablab/quast#63]
Hi, 

I recently have encountered an issue with a `Quast` analysis (version 5.0.0.dev0, 9ba434b). I'm having difficulty getting the `report.html` to fully load. The page hangs on the loading screen and remains blank. These are relatively small (150 Mbp) genomes and I haven't had any issues running `Quast` reports on a similar assembly with the same reference before. Can you offer any suggestions on how to get the full report to open?

These are the files present in the output directory. I appears that I am missing directories and files that were generated when I've run `Quast` in the past.
```
basic_stats/
contigs_reports/
quast_corrected_input/
quast.log
report.html
```

I am putting my log below. I realize that `matplotlib` is not loading, but I read that this only should affect PDF output. 

```
/usr/local/quast/quast.py /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/mnemiopsis.contigs.fasta /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/Mlei.contigs.fasta -R /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/MlScaffold09.fasta -o mlei_assembly1_quast5.0_results_3 --fragmented --circos

Version: 5.0.0.dev0, 9ba434b

System information:
  OS: Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-Ubuntu-16.04-xenial (linux_64)
  Python version: 2.7.12
  CPUs number: 28

Started: 2018-07-12 19:13:38

Logging to /ysm-gpfs/scratch60/zrl3/mnemiopsis/mnemiopsis_assembly_1/mlei_assembly1_quast5.0_results_3/quast.log
NOTICE: Maximum number of threads is set to 7 (use --threads option to set it manually)

CWD: /ysm-gpfs/scratch60/zrl3/mnemiopsis/mnemiopsis_assembly_1
Main parameters: 
  MODE: default, threads: 7, minimum contig length: 500, minimum alignment length: 65, \
  ambiguity: one, threshold for extensive misassembly size: 1000

WARNING: Can't draw plots: python-matplotlib is missing or corrupted.

Reference:
  /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/MlScaffold09.fasta ==> MlScaffold09

Contigs:
  Pre-processing...
  1  /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/mnemiopsis.contigs.fasta ==> mnemiopsis.contigs
  2  /ysm-gpfs/home/zrl3/scratch60/mnemiopsis/mnemiopsis_assembly_1/Mlei.contigs.fasta ==> Mlei.contigs

2018-07-12 19:13:50
Running Basic statistics processor...
  Reference genome:
    MlScaffold09.fasta, length = 155865547, num fragments = 5100, GC % = 38.86
  Contig files: 
    1  mnemiopsis.contigs
    2  Mlei.contigs
  Calculating N50 and L50...
    1  mnemiopsis.contigs, N50 = 75144, L50 = 627, Total length = 161086865, GC % = 39.21, # N's per 100 kbp =  0.00
    2  Mlei.contigs, N50 = 11936, L50 = 3653, Total length = 150339040, GC % = 38.86, # N's per 100 kbp =  1.45
Done.

2018-07-12 19:14:14
Running Contig analyzer...
  1  mnemiopsis.contigs
  1  Logging to files /ysm-gpfs/scratch60/zrl3/mnemiopsis/mnemiopsis_assembly_1/mlei_assembly1_quast5.0_results_3/contigs_reports/contigs_report_mnemiopsis-contigs.stdout and contigs_report_mnemiopsis-contigs.stderr...
  1  Aligning contigs to the reference
  1  /usr/local/quast/quast_libs/minimap2/minimap2 -c -x asm5 -B5 -O4,16 --no-long-join \
     -r 85 -N 50 -s 65 -z 200 --mask-level 0.9 --min-occ 200 -g 2500 --score-N 2 --cs \
     -t 3 mlei_assembly1_quast5.0_results_3/quast_corrected_input/MlScaffold09.fasta \
     mlei_assembly1_quast5.0_results_3/quast_corrected_input/mnemiopsis_contigs.fasta \
     > mlei_assembly1_quast5.0_results_3/contigs_reports/minimap_output/mnemiopsis-contigs.coords_tmp \
     2>> mlei_assembly1_quast5.0_results_3/contigs_reports/contigs_report_mnemiopsis-contigs.stderr
  2  Mlei.contigs
  2  Logging to files /ysm-gpfs/scratch60/zrl3/mnemiopsis/mnemiopsis_assembly_1/mlei_assembly1_quast5.0_results_3/contigs_reports/contigs_report_Mlei-contigs.stdout and contigs_report_Mlei-contigs.stderr...
  2  Aligning contigs to the reference
  2  /usr/local/quast/quast_libs/minimap2/minimap2 -c -x asm5 -B5 -O4,16 --no-long-join \
     -r 85 -N 50 -s 65 -z 200 --mask-level 0.9 --min-occ 200 -g 2500 --score-N 2 --cs \
     -t 3 mlei_assembly1_quast5.0_results_3/quast_corrected_input/MlScaffold09.fasta \
     mlei_assembly1_quast5.0_results_3/quast_corrected_input/Mlei_contigs.fasta > \
     mlei_assembly1_quast5.0_results_3/contigs_reports/minimap_output/Mlei-contigs.coords_tmp \
     2>> mlei_assembly1_quast5.0_results_3/contigs_reports/contigs_report_Mlei-contigs.stderr
  2  Analysis is finished.
```

**Comment by alexeigurevich** [comment]
Hi,
The `report.html` file could not be opened properly because it is not complete yet because the processing is not finished (according to the log). Actually, it should not be generated at this stage yet, so most likely this file is from some of your previous runs with the same output directory. The processing is finished when you see `Thank you for using QUAST!` message at the end of the log and section `RESULTS:` just above it (with the link to completed `report.html` and other report files).

According to the log, Quast is currently in the "Contig analyzer" stage (usually, the most time-consuming one). Only one out of two assemblies is processed (we see `2  Analysis is finished.` but `1  Analysis is finished.` is missing yet). Anyway, 150 Mbp genomes are not large for Quast 5.0, so it should finish pretty fast if everything is fine. 

I am closing this issue since there is no problem with opening `report.html` actually.
Please create another issue if the processing of `1  mnemiopsis.contigs` is still hanging. Provide us with `mlei_assembly1_quast5.0_results_3/contigs_reports/contigs_report_mnemiopsis-contigs.stderr` file in this case.

**Comment by zrlewis** [comment]
@alexeigurevich Okay. Thanks for the clarification!

**Comment by alexeigurevich** [comment]
@zrlewis thanks for reporting this, I think this issue may also help someone else in the future to figure out what is going on.

By the way, since your genome is relatively large (>100 Mbp), you may be interested in running Quast with `--large`. See more details at http://cab.spbu.ru/software/quast-lg/
