### ISSUE TITLE
--gene-finding not generating any results

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/quast#77]
I'm using `--gene-finding` with metaquast (v4.6.3), and I'm getting all output files without any errors. However, any of the summary files related to genes have no data. For instance:

```
$ cat summary/TSV/"#_genes.tsv"
Assemblies	athena.asm
Akkermansia_muciniphila_ATCC_BAA-835	-
Bacteroides_uniformis_CL03T12C37	-
Bacteroides_vulgatus	-
Butyrivibrio_crossotus_DSM_2876	-
Desulfovibrio_piger	-
Fusicatenibacter_saccharivorans	-
Methanobrevibacter_smithii_ATCC_35061	-
Ochrobactrum_anthropi	-
Parabacteroides_distasonis_ATCC_8503	-
Phascolarctobacterium_succinatutens_YIT_12067	-
Victivallis_vadensis	-
```

Maybe metaquast is silently failing when running the gene calling?

**Comment by alexeigurevich** [comment]
Note 1: gene prediction results should be in "#_predicted_genes_(unique).txt" report (or "num_predicted_genes_(unique).txt" since v.5.0.0). Simple "num_genes..." reports are about the number of found genes from the provided annotation file (`-G/--genes` option in v.4.6.3 and earlier, `-g/--features` option in v.5.0.0 and later).

Note 2: the fail of gene prediction module is not a critical error, so it is reported as a "non-fatal error" in the log and does not cause a crash of the entire pipeline. I suppose that the local GeneMark license file provided in the Quast package may be out of date already and that caused the crash of the MetaGeneMark prediction tool. You can update either solely the license file (`~/.gm_key` -- you can obtain the new file at  http://exon.gatech.edu/GeneMark/license_download.cgi after filling the license form; download the gzipped archive, unpack it and move to your ~/.gm_key file) or by updating Quast to the latest version (includes a new license file).

If I am wrong regardging Note 2 -- please reopen the issue and provide us `metaquast.log` and `combined_reference/quast.log` files from the output directory.
