### ISSUE TITLE
GeneMark license limitations

### ISSUE THREAD

**Issue by isgilman** [ablab/quast#84]
I'm trying to get quast up and running through conda and I've hit a wall with GeneMark. Here is the warning given by quast:

"WARNING: GeneMark tool can't be started because of license limitations!"

I saw that this was somewhat addressed in [#77](https://github.com/ablab/quast/issues/77), but the suggestions didn't solve my problem. I tried downloading a new version of GeneMark-ES and overwriting the old `~/.gm_key` and updating quast with `conda update quast`, but neither fixed the problem. I'm attaching the `quast.log` here if it helps.

Thanks, Ian

[quast.log](https://github.com/ablab/quast/files/2664230/quast.log)

**Comment by alexeigurevich** [comment]
Hi Ian,
Sorry for the delay! This is a great question to post here since I've answered it several times via our support email and now it is a good time to have it here as well for all new users facing the same issue.

The issue is not related to https://github.com/ablab/quast/issues/77. This is a known feature of `bioconda` installation. By design, we decided to disable and exclude GeneMark tools (see [this commit](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/quast/genemark-issue_disable-and-exclude-from-package.patch)) from our bioconda distribution due to license limitations. We have a license from GeneProbe Inc. to provide their tools in our package but in case of bioconda it is not clear whether we can redistribute GeneMark this way.

So, if you want to use GeneMark/GeneMark-ES/MetaGeneMark inside Quast and you are compiliant with their [license](http://topaz.gatech.edu/GeneMark/license_download.cgi), you should add missing files to your bioconda installation manually (or use regular Quast package from SourceForge, the latest is [here](https://sourceforge.net/projects/quast/files/latest/download)). The missing files are `quast_libs/genemark*` (take them from the GitHub repo or the regular SourceForge package), they should be placed under `<bioconda_installation_of_quast>/quast_libs/`. **Note the asterisk** -- you should copy `quast_libs/genemark/` and `quast_libs/genemark-es/` directories AND `quast_libs/genemark.py` file (the `bioconda` installation has this file but it contains `LICENSE_LIMITATIONS_MODE = True`. This means that the use of GeneMark is disabled and you see the WARNING message).

Let me know if something is not clear or not working!

**Comment by alexeigurevich** [comment]
Few examples of how `<bioconda_installation_of_quast>/quast_libs/` may look in practice:
`~/anaconda3/lib/python3.6/site-packages/quast_libs/` (Python 3.6, default environment)
`~/anaconda2/envs/bioinfo/lib/python2.7/site-packages/quast_libs/` (Python 2.7, `bioinfo` environment)

You may find the acutal path by running `quast.py --test` and check the first line in the log/on screen. There should be something like
`/home/username/anaconda3/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg-info/scripts/quast.py --test`

You need to copy the `quast.py` path and substitute  `quast-5.0.2-py3.6.egg-info/scripts/quast.py` with `quast_libs/`.  

P.S. Note that `which quast.py` will give you a short path like `/home/username/anaconda3/bin/quast.py` which is useless in this case.

**Comment by ReneKat** [comment]
Hello @alexeigurevich and thank you for the above instructions. 
I have the genemark files (genemark/ genemark-es/ genemark.py) in the quast_libs/ located at:
/Users/Owl/miniconda3/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg/quast_libs
However, when I run the metaquast.py --gene-finding ... command in an environment where quast 5.0.2 is installed 
quast                     5.0.2           py36pl526ha441bb4_1    bioconda

I still get the error saying "WARNING: GeneMark tool can't be started because of license limitations!"

Do I need to change the LICENSE_LIMITATIONS_MODE = True ? 

Any guidance would be very appreciated. Thank you for your time.
René

**Comment by cement-head** [comment]
@ReneKat Yes, change the line:

`LICENSE_LIMITATIONS_MODE = True`

to read

`LICENSE_LIMITATIONS_MODE = False`

**Comment by ReneKat** [comment]
Hi @cement-head and thanks for the reply.
I simply skirted the issue by installing quast from the Git repository. :)
`git clone https://github.com/ablab/quast.git`
Have a great day,
Rene

**Comment by TobiasWinter97** [comment]
> Hi [@cement-head](https://github.com/cement-head) and thanks for the reply. I simply skirted the issue by installing quast from the Git repository. :) `git clone https://github.com/ablab/quast.git` Have a great day, Rene

Thanks! I also git clone quast and it solves the problem!
