### ISSUE TITLE
GC content is not counted for combined reference 

### ISSUE THREAD

**Issue by cssulliv** [ablab/quast#98]
Hi,

I recently ran metaquast.py for 4 of my metagenomic samples (R1 and R2 contig files for each assembler). I am ultimately comparing 2 different assemblers and would like some input on how to get meaningful conclusions using the stats output from metaquast. In face value it appears that my metaspade assemblies ( 2 column values on the right that appear more blue than the left columns; see image below for reference) look to be the better assembler based on # of contigs generated and contig length. 

<img width="1440" alt="Screen Shot 2019-04-15 at 10 42 42 AM" src="https://user-images.githubusercontent.com/41393799/56164572-afad7d00-5f6c-11e9-812e-84aa1c63b774.png">

 Also, I am curious as to why over-all GC content for each of my sample contigs was not calculated? I have the GC% for each of the sample contigs to the references and the unaligned contigs but not the over all GC content. 

Lastly, does your research group have additional instructive materials for interpreting the stats apart from the manual? If so would it be possible for you to point to those sources so I can make better meaningful interpretations of the stats output :) 

Mahalo!

**Comment by alexeigurevich** [comment]
Hi!
We don't show overall GC content by design since it doesn't make much sense in case of metagenomes. Note that it is always a mix of many many various species with a wide range of GC contents. Average value means almost nothing :)

> Lastly, does your research group have additional instructive materials for interpreting the stats apart from the manual? If so would it be possible for you to point to those sources so I can make better meaningful interpretations of the stats output :)

Unfortunately, we don't have additional materials (but probably should prepare them in the future since your question is a rather common one). At the moment, I may recommend you to additionally look at our [MetaQuast paper](https://academic.oup.com/bioinformatics/article/32/7/1088/1743987) and also at [CAMI paper](https://www.nature.com/articles/nmeth.4458) -- both are in open acess.
